server:
  port: 8090

spring:
  application:
    name: ASSIGNMENT-GATEWAY

  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Content-Length

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: user-service
          uri: lb://ASSIGNMENT-BUDDY-USER-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: pdf-service
          uri: lb://PDF-SERVICE
          predicates:
            - Path=/api/pdf/**

        - id: ai-service
          uri: lb://AI-SERVICE
          predicates:
            - Path=/api/ai/**